services:
- type: web
  name: chase-rice-fanclub
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app -c gunicorn_config.py
  postdeployCommand: python -c "import app; app.init_db()"